# Generated by Django 5.0.7 on 2024-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='content',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
