# Generated by Django 5.0.7 on 2024-07-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
