# Generated by Django 5.0.7 on 2024-07-11 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_user_groups_user_user_permissions_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
